name: industrial_ci

on:
  push:
    paths-ignore:
      - '.docker/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.docker/**'
      - '**.md'
  workflow_dispatch:

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
